# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shuttle_stations', '0002_remove_shuttlestation_direction_options'),
        ('direction_options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionoption',
            name='shuttle_station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shuttle_stations.ShuttleStation'),
        ),
    ]
