# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('direction_options', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('direction_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shuttle_stations', to='direction_options.DirectionOption')),
            ],
        ),
    ]
