# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170407_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='index_number',
            field=models.CharField(max_length=14),
        ),
    ]
