# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
        ('topups', '0002_auto_20170227_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='voucher_code',
        ),
        migrations.AddField(
            model_name='topup',
            name='voucher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topups', to='vouchers.Voucher'),
        ),
    ]
