# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topups', '0004_auto_20170516_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='network',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='topup',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
