# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20170227_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
