# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_driver_car_number'),
        ('users', '0002_auto_20170407_2207'),
        ('shuttle_stations', '0002_remove_shuttlestation_direction_options'),
        ('direction_options', '0003_auto_20170505_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.DateTimeField()),
                ('accepted_time', models.DateTimeField()),
                ('direction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='direction_options.DirectionOption')),
                ('driver_accepted_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver')),
                ('shuttle_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='shuttle_stations.ShuttleStation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
            ],
        ),
    ]
