# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alert_statuses', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alert_statuses.AlertStatus'),
        ),
    ]
