# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-14 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='driver_accepted_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.Driver'),
        ),
    ]
