# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-17 00:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20170514_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
    ]
