# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=12)),
                ('is_active', models.BooleanField(default=1)),
            ],
        ),
    ]
