# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_voucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
