# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0003_driver_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('driver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shuttle_locations', to='drivers.Driver')),
            ],
        ),
    ]
